site:
  title: Apiman Documentation
  url: https://www.apiman.io/apiman-docs
  start_page: guides::index.adoc
  robots: allow
  keys:
    google_analytics: "G-TRD82LC9Y2"

content:
  sources:
    - url: https://github.com/apiman/apiman.git
      branches:
        - master
        - 3.x
      start_path: docs

    - url: https://github.com/apiman/apiman.git
      branches:
        - master
        - 3.x
      start_path: docs/migration

    - url: https://github.com/apiman/apiman.git
      branches:
        - master
        - 3.x
      start_path: docs/installation

    - url: https://github.com/apiman/apiman.git
      branches:
        - master
        - 3.x
      start_path: docs/user

    - url: https://github.com/apiman/apiman.git
      branches:
        - master
        - 3.x
      start_path: docs/development

    # DEPRECATED -- just for 2x — we will sunset this ASAP.
    - url: https://github.com/apiman/apiman-docs-user-guide.git
      branches:
        - 1.x
        - 2.x
    - url: https://github.com/apiman/apiman-docs-installation-guide.git
      branches:
        - 1.x
        - 2.x
    # END DEPRECATED

ui:
  bundle:
    url: https://github.com/apiman/apiman-antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll

output:
  dir: ./docs

asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''
    hide-uri-scheme: '@'
    idseparator: '-'
    idprefix: ''
  extensions:
  - ./lib/openblock.js
  - ./lib/tabs-block.js

urls:
  latest_version_segment: latest
  latest_prerelease_version_segment: dev
  latest_version_segment_strategy: redirect:to
