site:
  title: Apiman Documentation
  url: https://www.apiman.io/apiman-docs
  start_page: welcome::index.adoc
  keys:
    google_analytics: "UA-56678850-3"

content:
  sources:
    - url: ./
      branches:
        - 1.x
        - 2.x
        - HEAD
    - url: ../apiman-docs-user-guide
      branches:
        - 1.x
        - 2.x
        - antora
    - url: ../apiman-docs-installation-guide
      branches:
        - 1.x
        - 2.x
        - antora
    - url: ../apiman
      branches:
        - 1.x
        - 2.x
        - HEAD
      start_path: docs

ui:
  bundle:
    url: https://github.com/apiman/apiman-antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll

output:
  dir: ./docs

asciidoc:
  attributes:
    apiman-version-release: 3.0.0-SNAPSHOT
    wildfly-version: 23.0.2.Final
    wildfly-major-version: 23
    keycloak-version: 18.0.2
    page-pagination: true
  extensions:
  - ./lib/openblock.js
  - ./lib/tabs-block.js
