site:
  title: Apiman Documentation
  url: https://www.apiman.io/apiman-docs
  start_page: guides::index.adoc
  robots: allow
  keys:
    google_analytics: "UA-56678850-3-do-not-use-locally"

content:
  sources:
    - url: ../apiman
      branches:
        - master
        - 3.x
      start_path: docs

    - url: ../apiman
      branches:
        - master
        - 3.x
      start_path: docs/migration

    - url: ../apiman
      branches:
        - master
        - 3.x
      start_path: docs/installation

    - url: ../apiman
      branches:
        - master
        - 3.x
      start_path: docs/user

    - url: ../apiman
      branches:
        - master
        - 3.x
      start_path: docs/development

ui:
  bundle:
    url: https://github.com/apiman/apiman-antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll

output:
  dir: ./docs

asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''
    hide-uri-scheme: '@'
    idseparator: '-'
    idprefix: ''
  extensions:
  - ./lib/openblock.js
  - ./lib/tabs-block.js

urls:
  latest_version_segment: latest
  latest_prerelease_version_segment: dev
  latest_version_segment_strategy: redirect:to
